# Generated by Django 6.0.8 on 2026-09-15 05:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('8000.00'), max_digits=12, verbose_name='Acquisition Cost (CAC)'),
        ),
        migrations.AddField(
            model_name='designer',
            name='follow_up_tasks',
            field=models.JSONField(blank=True, default=list, help_text="List of tasks: [{'id': 1, 'title': '...', 'due_date': 'YYYY-MM-DD', 'completed': False}]", verbose_name='Follow-up Tasks'),
        ),
        migrations.AddField(
            model_name='designer',
            name='health_score',
            field=models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Health Score (0-100)'),
        ),
        migrations.AddField(
            model_name='designer',
            name='lead_source',
            field=models.CharField(blank=True, default='Referral', help_text='Example: Referral, Instagram, Trade show, Direct outreach, Inbound', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='designer',
            name='lifetime_gmv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Lifetime GMV'),
        ),
        migrations.AddField(
            model_name='designer',
            name='lost_reason',
            field=models.CharField(blank=True, help_text='Reason when a lead or contract is marked lost.', max_length=255, null=True, verbose_name='Lost Reason'),
        ),
        migrations.AddField(
            model_name='designer',
            name='monthly_gmv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monthly GMV'),
        ),
        migrations.AddField(
            model_name='designer',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Follow-up Date'),
        ),
        migrations.AddField(
            model_name='designer',
            name='renewal_likelihood',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Renewal Likelihood (%)'),
        ),
        migrations.AddField(
            model_name='designer',
            name='sales_owner',
            field=models.CharField(blank=True, default='Nisha Kapoor', help_text='Internal sales representative assigned to this designer.', max_length=150, verbose_name='Sales Owner'),
        ),
    ]
