# Generated by Django 6.0.8 on 2026-09-15 05:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_designer_acquisition_cost_designer_follow_up_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='sku_productivity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='SKU Productivity'),
        ),
    ]
