# Generated by Django 5.2 on 2026-09-22 09:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_designer_sku_productivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Account number must contain 9 to 18 digits.', regex='^[0-9]{9,18}$')], verbose_name='Bank Account Number')),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code')),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-character PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')], verbose_name='PAN Number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Account Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='designers.designer', verbose_name='Designer')),
            ],
            options={
                'verbose_name': 'Designer Account Details',
                'verbose_name_plural': 'Designer Account Details',
                'db_table': 'designer_account_details',
                'ordering': ['-updated_at'],
            },
        ),
    ]
