# Generated by Django 5.2 on 2026-09-23 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_designeraccountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GST number.', regex='^[0-9A-Z]{15}$')], verbose_name='GST Number'),
        ),
    ]
