# Generated by Django 5.2 on 2026-09-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_alter_designer_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='offline_membership_plan',
            field=models.CharField(blank=True, choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium')], db_index=True, help_text='Offline fashion credit membership plan selected by the designer.', max_length=20, null=True, verbose_name='Offline Membership Plan'),
        ),
        migrations.AddField(
            model_name='designer',
            name='online_membership_plan',
            field=models.CharField(blank=True, choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('PALLADIUM', 'Palladium')], db_index=True, help_text='Online fashion credit membership plan selected by the designer.', max_length=20, null=True, verbose_name='Online Membership Plan'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['online_membership_plan'], name='designer_online__55099b_idx'),
        ),
        migrations.AddIndex(
            model_name='designer',
            index=models.Index(fields=['offline_membership_plan'], name='designer_offline_1a5e82_idx'),
        ),
    ]
