# Generated by Django 6.0.8 on 2026-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0006_designer_offline_membership_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='credit_points',
            field=models.PositiveBigIntegerField(default=0, help_text='Online fashion credit points allocated to this designer.', verbose_name='Given Credit Points'),
        ),
    ]
