# Generated by Django 6.0.8 on 2026-09-28 06:03

import django.core.files.storage
import django.core.validators
import pathlib
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_mediajob_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='growth_social_promotion',
            field=models.BooleanField(default=False, verbose_name='Exclusive Social Media Promotion (5,000 pts)'),
        ),
        migrations.AddField(
            model_name='product',
            name='growth_video_shoot',
            field=models.BooleanField(default=False, verbose_name='Exclusive Video & Photo Shoot (5,000 pts)'),
        ),
        migrations.AddField(
            model_name='product',
            name='social_media_campaign_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Social Media / Reel URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='social_media_notes',
            field=models.TextField(blank=True, default='', verbose_name='Social Media Team Notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='social_media_shoot_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shoot Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='social_media_status',
            field=models.CharField(choices=[('NONE', 'No Growth Add-on'), ('PENDING_REVIEW', 'Pending Review'), ('SHOOT_SCHEDULED', 'Shoot Scheduled'), ('IN_PRODUCTION', 'In Production'), ('CONTENT_READY', 'Content Ready'), ('PROMOTION_ACTIVE', 'Live / Promotion Active'), ('COMPLETED', 'Completed')], db_index=True, default='NONE', max_length=30, verbose_name='Social Media Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fulfilment_location',
            field=models.CharField(choices=[('MUMBAI_FC', 'Mumbai FC'), ('BENGALURU_FC', 'Bengaluru FC'), ('BANGALORE_FC', 'Bangalore FC'), ('KOCHI_FC', 'Kochi FC'), ('CHENNAI_FC', 'Chennai FC'), ('DELHI_FC', 'Delhi FC'), ('DESIGNER_STUDIO', 'Designer Studio')], max_length=100, verbose_name='Fulfilment Location'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Lenovo/PycharmProjects/Zenve_Fashion_Crm/fashion_crm/Zenve_Fashion_Backend/private_uploads')), upload_to=products.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
