# Generated by Django 5.2 on 2026-10-05 07:34

import django.core.files.storage
import django.core.validators
import pathlib
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_growth_social_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Lenovo T470/Desktop/zenve_fashion_crm/fashion_crm/Zenve_Fashion_Backend/private_uploads')), upload_to=products.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
