# Generated by Django 5.2 on 2026-09-26 05:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Batch ID'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='disbursed_by',
            field=models.CharField(blank=True, default='Finance Controller', max_length=150, null=True, verbose_name='Disbursed By'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_gateway_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Payment Gateway Fee / MDR'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payout_channel',
            field=models.CharField(blank=True, default='HDFC Corporate Primary A/C', max_length=100, null=True, verbose_name='Payout Channel / Account'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI Payout'), ('RazorpayX', 'RazorpayX Payout'), ('Escrow Release', 'Escrow Release'), ('COD Courier Offset', 'COD Courier Offset'), ('Cheque', 'Cheque / DD')], default='Bank Transfer', max_length=50, null=True, verbose_name='Payout Method'),
        ),
    ]
