# Generated by Django 6.0.8 on 2026-10-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_settlement_batch_id_settlement_disbursed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('SIZE_FIT', 'Size Issue'), ('COLOR_MISMATCH', 'Color Mismatch'), ('DEFECTIVE', 'Defective Product'), ('NOT_EXPECTED', 'Not as Expected'), ('DAMAGE_DELIVERY', 'Damage during Delivery'), ('WRONG_ITEM', 'Wrong Product'), ('QUALITY_ISSUE', 'Quality Not as Expected'), ('NOT_NEEDED', 'No Longer Needed'), ('OTHER', 'Other')], default='SIZE_FIT', max_length=50, verbose_name='Reason for Return'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('RECEIVED', 'Received at Warehouse'), ('INSPECTED_PASSED', 'Inspected - Passed'), ('INSPECTED_FAILED', 'Inspected - Failed QC'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected'), ('EXCHANGE', 'Exchange'), ('PROCESSED', 'Processed')], db_index=True, default='REQUESTED', max_length=30, verbose_name='Return Status'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=60, unique=True, verbose_name='Tracking Number')),
                ('order_number', models.CharField(blank=True, default='', max_length=60, verbose_name='Order Number')),
                ('customer_name', models.CharField(default='Guest Customer', max_length=150, verbose_name='Customer Name')),
                ('customer_avatar', models.CharField(blank=True, default='', max_length=350, verbose_name='Customer Avatar URL')),
                ('courier', models.CharField(choices=[('Delhivery', 'Delhivery'), ('Ekart', 'Ekart'), ('Blue Dart', 'Blue Dart'), ('DTDC', 'DTDC'), ('XpressBees', 'XpressBees')], default='Delhivery', max_length=50, verbose_name='Courier Partner')),
                ('status', models.CharField(choices=[('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Exception', 'Exception'), ('RTO', 'RTO')], default='In Transit', max_length=50, verbose_name='Shipment Status')),
                ('expected_delivery', models.CharField(blank=True, default='', max_length=60, verbose_name='Expected Delivery Date')),
                ('origin_hub', models.CharField(default='Bangalore Hub', max_length=100, verbose_name='Origin Hub')),
                ('destination_hub', models.CharField(default='Regional Delivery Centre', max_length=100, verbose_name='Destination Hub')),
                ('destination_address', models.TextField(blank=True, default='', verbose_name='Destination Address')),
                ('timeline', models.JSONField(blank=True, default=list, verbose_name='Tracking Timeline Events')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'orders_shipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
