# Generated by Django 6.0.8 on 2026-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_returnrequest_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Customer Phone'),
        ),
    ]
