# Generated by Django 6.0.7 on 2026-09-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleLayerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('01', '01 - Designer CRM'), ('02', '02 - Designer Portal'), ('03', '03 - Product / SKU'), ('04', '04 - Catalogue QA'), ('05', '05 - Inventory Engine'), ('06', '06 - Storefront'), ('07', '07 - OMS'), ('08', '08 - Delivery Engine'), ('09', '09 - Returns Engine'), ('10', '10 - Settlement'), ('11', '11 - BI Dashboards'), ('12', '12 - Command Centre')], max_length=2)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_access', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Layer Access',
                'verbose_name_plural': 'Role Layer Access',
                'ordering': ['role__name', 'layer'],
                'unique_together': {('role', 'layer')},
            },
        ),
    ]
